# -1.0 jobs
# -1.1 guilds
# -1.2 general xp
# -1.3 scoreboard; 1.3.1 config level up
# 2.0 MAJ 23/01/2021 -> mana + aptitudes + sorts
main: fr.overcraftor.mmo.Main
name: MMORPG
version: 2.0-SNAPSHOT
author: Overcraftor
database: true
description: "Discord: Overcraftor#4841 | Plugin MMO pour le serveur Monster-MC | Commande par Azrotho fait par Overcraftor avec <3"
api-version: 1.14
depend: [PlaceholderAPI]

commands:
  # JOBS
  jobs:
    description: Commande pour voir l'avancement des jobs
    aliases: [j, job]
  addxpjobs:
    description: Commande pour ajouter de l'exp d'un job a un joueur
    aliases: addxpjob
  setxpjobs:
    description: Commande pour definir l'exp d'un job d'un joueur
    aliases: setxpjob

  # GUILDS
  guild:
    description: Domaine pour les commandes de guilds
    aliases: g

  # GENERAL XP
  addxp:
    description: Command pour ajouter de l'exp a un joueur
  setxp:
    description: Commande pour definir l'exp d'un joueur

  # APTITUDES
  addaptitude:
    description: Command pour ajouter de l'aptitude a un joueur
    aliases: addapt
  setaptitude:
    description: Command pour definir l'aptitude d'un joueur
    aliases: setapt
  competance:
    description: Command pour ouvrir le menu des competences
    aliases: comp

  #  MANA
  addmaxmana:
    description: Ajouter du mana max a un joueur
    aliases: amm
  setmaxmana:
    description: Definir le mana max d'un joueur
    aliases: smm
  addmana:
    description: Ajouter du mana a un joueur
    aliases: am
  setmana:
    description: Definir le mana  d'un joueur
    aliases: setm

  mmo:
    description: Commande administrative
    aliases: mmorpg

  wimr:
    description: Voir sa region WorldGuard